### ISSUE TITLE
Update hackage release to support base 4.9 & ghc-8

### ISSUE THREAD

**Issue by YellowOnion** [peddie/pipes-zeromq4#1]
The current release on hackage doesn't work with base-4.9, or ghc-8.

**Comment by peddie** [comment]
Thanks for reporting; I'll try to get to this at the weekend.  Haven't had to look into this code since I released it . . .

**Comment by peddie** [comment]
This should be fixed with 0.3.0.0 on Hackage.  Travis is now testing it against GHC HEAD and 8.0.2.  (Interestingly the only bound that needed to be adjusted was that of the `pipes` package, not `base`!)  Please reopen if you have any trouble.
